sff_lexique:
    resource: "@SffLexiqueBundle/Resources/config/routing.yml"
    prefix:   /

sff_publicite:
    resource: "@SffPubliciteBundle/Resources/config/routing.yml"
    prefix:   /

sff_liens:
    resource: "@SffLiensBundle/Resources/config/routing.yml"
    prefix:   /

sff_admin:
    resource: "@SffAdminBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
